
; 2 sprites generated with spritemate on 6/27/2021, 9:39:43 PM
; Byte 64 of each sprite contains multicolor (high nibble) & color (low nibble) information

.data

sprites:

sprite_0:
.byte $00,$00,$00,$00,$18,$00,$00,$18
.byte $00,$00,$18,$00,$00,$3c,$00,$00
.byte $24,$00,$00,$24,$00,$00,$24,$00
.byte $00,$24,$00,$00,$3c,$00,$20,$3c
.byte $04,$20,$7e,$04,$20,$ff,$04,$23
.byte $ff,$c4,$27,$ff,$e4,$3f,$ff,$fc
.byte $3f,$ff,$fc,$3f,$ff,$fc,$3c,$18
.byte $3c,$00,$3c,$00,$00,$3c,$00,$03
