;==============================================================================
; RetroGameDev Library C64 v1
;   (C)2017 by Derek Morris <https:;retrogamedev.com>
;   Conversion to KickAss 5.x by Marcelo Lv Cabral <http://lvcabral.com>
;   Conversion to ca65 by Rob Prouse <https://alteridem.net>
;==============================================================================
; Includes

.ifndef _LIB_INCLUDES_
_LIB_INCLUDES_ = 1

.include "libMemory.inc"
.include "libMath.inc"
.include "libInput.inc"
.include "libScreen.inc"
.include "libSound.inc"
.include "libSprite.inc"

.endif ; _LIB_INCLUDES_
