all: basic-computer-games more-basic-computer-games
	$(MAKE) -C basic-computer-games $(MAKECMDGOALS) all
	$(MAKE) -C more-basic-computer-games $(MAKECMDGOALS) all

clean:
	$(MAKE) -C basic-computer-games $(MAKECMDGOALS) clean
	$(MAKE) -C more-basic-computer-games $(MAKECMDGOALS) clean
